version: "3"
services:
  cities:
    build: ./cities
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw